### ISSUE TITLE
Otto Event Bus

### ISSUE THREAD

**Issue by karthikb351** [saurabhsjoshi/VITacademics-for-Android#24]
Can we use an event bus like [Otto](https://github.com/square/otto) to handle the data refreshes? Since it's completely in the background now, we need a better mechanism for updating the fragment the user is currently in. This simplifies the entire thing.

Please @saurabhsjoshi, just one more library? Pretty please? :ice_cream:

**Comment by aneesh-neelam** [comment]
Could this be implemented soon? I hear the app is crashing in some cases, during refresh.

**Comment by saurabhsjoshi** [comment]
App crash is not related to this. Karthik can implement this.

**Comment by aashrairavooru** [comment]
I would recommend using greenrobots event bus much lighter and assertive in use

**Comment by karthikb351** [comment]
Added in a6f558b0f235acdaccc474664d21f611607266c6
