### ISSUE TITLE
No Courses Registered

### ISSUE THREAD

**Issue by aneesh-neelam** [saurabhsjoshi/VITacademics-for-Android#28]
Can the app handle the case when no courses are registered?

**Comment by saurabhsjoshi** [comment]
Maybe yes

**Comment by aneesh-neelam** [comment]
The courses key will have an empty array as value. Although this has been implemented only on the [development branch](https://github.com/aneesh-neelam/VITacademics/tree/development) of the [backend](https://github.com/aneesh-neelam/VITacademics). Hence, the app must be updated for the new JSON format in #32.

**Comment by saurabhsjoshi** [comment]
That's fine if there is no course, the for loop will just break out and the app won't crash. And we don't really need to worry about this.

**Comment by aneesh-neelam** [comment]
Alright.
