### ISSUE TITLE
API Usage for Refresh

### ISSUE THREAD

**Issue by aneesh-neelam** [saurabhsjoshi/VITacademics-for-Android#30]
Whenever a user refreshes, please call '/data/refresh'. Only if you get "Session timed out", then call '/login/auto' and '/data/refresh'. 

If session is still valid, you get cached data on '/data/refresh'. Otherwise you'll get "Session timed out" (which means the cookie is removed from in-memory cache) almost instantaneously. Hence, it's overhead is negligible.

**Comment by saurabhsjoshi** [comment]
Isn't this handled by the server itself?

**Comment by aneesh-neelam** [comment]
No, the server resets the session when you call '/login/auto', I implemented it like this to force a proper refresh if needed.
