### ISSUE TITLE
Ambiguous Messages

### ISSUE THREAD

**Issue by aneesh-neelam** [saurabhsjoshi/VITacademics-for-Android#31]
Remove irrelevant messages like "PBL/Lab Marks Unsupported". Its misleading as all kinds of marks are supported now. If marks are not present, please say something like "Marks are unavailable at this time"/"Marks are unavailable for this kind of course"(For PBC) to avoid ambiguity.

**Comment by saurabhsjoshi** [comment]
Not supported meaning there is no UI as of now in Android to show the marks. I'll change it nevertheless.
