### ISSUE TITLE
Update Friends Share JSON API

### ISSUE THREAD

**Issue by aneesh-neelam** [saurabhsjoshi/VITacademics-for-Android#32]
I have updated the JSON format for "Sharing Timetable with Friends" in the [development branch](https://github.com/aneesh-neelam/VITacademics/tree/development) of the [backend](https://github.com/aneesh-neelam/VITacademics). 

Check sample data from [here](https://github.com/aneesh-neelam/VITacademics/tree/development/api/sample-data) and update app's JSON parsers accordingly.

**Comment by saurabhsjoshi** [comment]
Don't change it! Leave it as it is. I'll have to do lot of changes to make the app compatible again.

**Comment by aneesh-neelam** [comment]
I have only removed the additional "data" key and put "courses" and "timetable" in the root, just like 'data/first' and '/data/refresh'.

**Comment by aneesh-neelam** [comment]
@saurabhsjoshi: You sure this is too much work? Because, it seems like a minor change only.

**Comment by saurabhsjoshi** [comment]
Inside the app the friend object even has the Facebook Profile picture and other fb data which I load once I get other info from server. So I will have to change all references in the fb related code and I am currently really busy.
