### ISSUE TITLE
Decouple google play services

### ISSUE THREAD

**Issue by aashrairavooru** [saurabhsjoshi/VITacademics-for-Android#35]
Google has decoupled google play services as it is one monolith of a library http://developer.android.com/google/play-services/setup.html 

Since you guys are only using gcm and google analytics using gms:play-services-base:6.5.87 will greatly reduce the size of the app and the memory consumed by the app

**Comment by karthikb351** [comment]
Implemented via a6f558b0f235acdaccc474664d21f611607266c6

**Comment by aashrairavooru** [comment]
upgraded to 7.0.0 and gcm only play services in #39
