### ISSUE TITLE
Implementing dagger

### ISSUE THREAD

**Issue by aashrairavooru** [saurabhsjoshi/VITacademics-for-Android#38]
We should be using dagger 2 in out project to reduce the amount of code, i have already started implementing it, @karthikb351 any heads up for me??

**Comment by karthikb351** [comment]
Do we have a big enough use case for this to be useful?
It does make everything look neater though.

We still aren't stable on how the various components of this app are going to come together, it's in really early stages. My suggestion would be to revisit this later, once we have a proper structure?

At that point, we can move everything to modules in Dagger.

**Comment by aashrairavooru** [comment]
We will get a good structure once we use dagger,it will improve our
development speed significantly as well

**Comment by aashrairavooru** [comment]
If we use dagger we should do it now since we are rewriting shifting a
massive codebase to dagger will be really difficult

**Comment by karthikb351** [comment]
Okay, fair enough.
I've not used dagger before, send a PR with some small part of it done, and we'll move forward from there?

**Comment by aashrairavooru** [comment]
Cool

**Comment by aashrairavooru** [comment]
added in #39

**Comment by aashrairavooru** [comment]
If you want to see the code generated by dagger,clone the dagger branch,build the code and see the generated code in build folder,should give you a good idea of whats happening
