### ISSUE TITLE
Uneven time left in class shown in app.

### ISSUE THREAD

**Issue by rahulkapoor90** [saurabhsjoshi/VITacademics-for-Android#40]
I don't know if it's fixed but the app doesn't show proper time left in the next class.
for eg. if one sees the app at 7:00 am and the class is on 9:00 am it shows 2 hrs left but when app is opened at 7:02 am or something like that it shows only 1 hr left.

**Comment by aneesh-neelam** [comment]
@rahulkapoor90: Why close the issue? It hasn't been resolved yet.
