### ISSUE TITLE
Contributors?

### ISSUE THREAD

**Issue by aneesh-neelam** [saurabhsjoshi/VITacademics-for-Android#43]
Hey, @kishore-narendran and I, @aneesh-neelam wish to contribute to this app. 

Since you guys are lazy, busy or sometimes retarded, we have decided to  contribute and release a new *working* version of the VITacademics Android app. 

@kishore-narendran and I, @aneesh-neelam have done/are doing/will do the following courses: 
* [Developing Android Apps](https://www.udacity.com/course/ud853)
* [Android Performance](https://www.udacity.com/course/ud825)
* [UX Design for Mobile Developers](https://www.udacity.com/course/ud849)

All of the above courses are by Google themselves, so that gives them quite a bit of credibility. Also, unlike other "tutorials" on the internet, this explains things very well and is not a "copy-paste code lab" as they say. 

@karthikb351: Please do guide us regarding the best ways to do things though. You have seen how well we worked for the Final Year Project Review II, you know we can do this. 

Our GitHub fork is [here](https://github.com/aneesh-neelam/VITacademics-Android).

**Comment by kishore-narendran** [comment]
Where is the need for this. *facepalm*

-----Original Message-----

**Comment by aneesh-neelam** [comment]
@kishore-narendran: You mean issue? Well, I want to have a place where we can discuss who is doing what. Also, I need @karthikb351 to tell me how much of the app is done and what is left.

**Comment by CoderHam** [comment]
@gauravagerwala (Gaurav Agerwala) and I, @CoderHam (Hemant Jain) would like to contribute to the Academics Android app. We are 2nd years here at VIT and have experience with Android app dev. We would really appreciate it if you brief us on what all is to be implemented and how to proceed with the same. 
Cheers.

**Comment by karthikb351** [comment]
@CoderHam and @gauravagerwala. Awesome. Can you guys get on chat at https://scrollback.io/vitacademics? We can discuss there.
