### ISSUE TITLE
Spinner in Subject Details

### ISSUE THREAD

**Issue by saurabhsjoshi** [saurabhsjoshi/VITacademics-for-Android#5]

**Comment by aashrairavooru** [comment]
why are there so many text views in that fragment anyways, isn't it better to have a single text view and just use new lines, and for a dropdown effect just use a simple animation why suffer with all the boilerplate for spinner

**Comment by aneesh-neelam** [comment]
@aashrairavooru: This isn't relevant.

**Comment by aashrairavooru** [comment]
wow didn't notice the date sorry for that
